# Generated by Django 5.0.2 on 2024-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prod_origin', models.CharField(max_length=100)),
                ('prod_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
