# Generated by Django 5.0.2 on 2024-02-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
