# Generated by Django 5.0.2 on 2024-03-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='user_name',
            new_name='username',
        ),
    ]
