# Generated by Django 5.0.2 on 2024-03-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userregister_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
